FROM ubuntu
ENV MON_MESSAGE="coucou"
ENTRYPOINT echo Mon message est : $MON_MESSAGE


# docker build -t ubuntuperso .

# test de l'image
# docker run ubuntuperso
# resultat dans la console : Mon message est : coucou
# docker run -e MON_MESSAGE="salut" ubuntuperso
# resultat dans la console : Mon message est : salut
