// <auto-generated />
using Correction02Hotel.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Correction02Hotel.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240122125742_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Correction02Hotel.Models.Chambre", b =>
                {
                    b.Property<int>("Numero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Numero"), 1L, 1);

                    b.Property<int>("NombreLits")
                        .HasColumnType("int");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.Property<decimal>("Tarif")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.HasKey("Numero");

                    b.ToTable("Chambres");

                    b.HasData(
                        new
                        {
                            Numero = 1,
                            NombreLits = 2,
                            Statut = 0,
                            Tarif = 100.50m
                        },
                        new
                        {
                            Numero = 2,
                            NombreLits = 4,
                            Statut = 2,
                            Tarif = 400.50m
                        });
                });

            modelBuilder.Entity("Correction02Hotel.Models.Client", b =>
                {
                    b.Property<int>("Identifiant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Identifiant"), 1L, 1);

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NumeroTelephone");

                    b.HasKey("Identifiant");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Identifiant = 1,
                            Nom = "Mairesse",
                            Prenom = "Guillaume",
                            Telephone = "0607080910"
                        },
                        new
                        {
                            Identifiant = 2,
                            Nom = "Dieudonné",
                            Prenom = "Antoine",
                            Telephone = "0607080911"
                        });
                });

            modelBuilder.Entity("Correction02Hotel.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ClientIdentifiant")
                        .HasColumnType("int");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientIdentifiant");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("Correction02Hotel.Models.ReservationChambre", b =>
                {
                    b.Property<int>("ChambreNumero")
                        .HasColumnType("int");

                    b.Property<int>("ReservationId")
                        .HasColumnType("int");

                    b.HasKey("ChambreNumero", "ReservationId");

                    b.HasIndex("ReservationId");

                    b.ToTable("ReservationChambres");
                });

            modelBuilder.Entity("Correction02Hotel.Models.Reservation", b =>
                {
                    b.HasOne("Correction02Hotel.Models.Client", "Client")
                        .WithMany("Reservations")
                        .HasForeignKey("ClientIdentifiant")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Correction02Hotel.Models.ReservationChambre", b =>
                {
                    b.HasOne("Correction02Hotel.Models.Chambre", "Chambre")
                        .WithMany("ReservationChambres")
                        .HasForeignKey("ChambreNumero")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Correction02Hotel.Models.Reservation", "Reservation")
                        .WithMany("ReservationChambres")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chambre");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("Correction02Hotel.Models.Chambre", b =>
                {
                    b.Navigation("ReservationChambres");
                });

            modelBuilder.Entity("Correction02Hotel.Models.Client", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("Correction02Hotel.Models.Reservation", b =>
                {
                    b.Navigation("ReservationChambres");
                });
#pragma warning restore 612, 618
        }
    }
}
