// <auto-generated />
using Demo01.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Demo01.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240207103903_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Demo01.Models.Crepe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double>("Diameter")
                        .HasColumnType("float");

                    b.Property<bool>("IsSalty")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Topping1")
                        .HasColumnType("int");

                    b.Property<int>("Topping2")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Crepes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Diameter = 14.0,
                            IsSalty = true,
                            Name = "Surprise du chef",
                            Topping1 = 4,
                            Topping2 = 8
                        },
                        new
                        {
                            Id = 2,
                            Diameter = 14.0,
                            IsSalty = true,
                            Name = "Fruits de la mer",
                            Topping1 = 3,
                            Topping2 = 0
                        },
                        new
                        {
                            Id = 3,
                            Diameter = 14.0,
                            IsSalty = false,
                            Name = "Double nut",
                            Topping1 = 0,
                            Topping2 = 0
                        },
                        new
                        {
                            Id = 4,
                            Diameter = 14.0,
                            IsSalty = false,
                            Name = "Myrtille",
                            Topping1 = 5,
                            Topping2 = 5
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
